apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  containers:
    - name: registry
      image: my-registry:5000/my-busybox
      command: ["sh","-c"]
      args: ["while true; echo 'Hello'; sleep 3;"]
  imagePullSecrets:
    - name: my-registry
